### PR TITLE
Rvizconfigtopdownortho

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
I set the default in rviz to be the topdown ortho view.

### CODE REVIEW

**Comment by Timple** [comment]
Looks like Rayman did instead of Matthijs ;-)

And more important than the what is usually the why.

**Comment by LoyVanBeek** [comment]
Why tho? I don't care for this at all. Especially since this PR has a conflict and is so minor in both code and convenience/inconvenience, I'm highly inclined to close it.

**Comment by MatthijsBurgh** [comment]
Max did this!!!

**Comment by MatthijsBurgh** [comment]
@MaxBaeten, it would stil be XYOrbit right?

**Comment by Rayman** [comment]
How can this happen? On all PCs with user `amigo`, git will prompt before committing. Hmm o wait, the git-hooks need to be installed...

**Pull request closed without merging**
