### PR TITLE
[DO NOT MERGE YET] Add ED layer to gmapping costmaps, fixing tue-robotics/tue_robocup#426

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Please take a extra careful look at tracking unknown space. This property isn't the same in all costmap files. I am not really familiar with the functions of it.

I only copied the layers from other configurations and checked the working, which seems to be working.

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
fixing tue-robotics/tue_robocup#426

**Review by jlunenburg — COMMENTED** [review]
Test on real robot, discuss with @reinzor

**Comment by MatthijsBurgh** [comment]
I tested it during a demo in the lab. Which gave some problems. Because the ED map is bigger than the Gmapping map, the planner allows to drive in unknown space. Plus the order of the layers does influence the behaviour.

**Comment by reinzor** [comment]
Will close this PR for now

**Pull request closed without merging**
