### PR TITLE
Use initial pose from env variables

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by reinzor** [comment]
What is the motivation? Environment variables are usually making things more complex

**Comment by MatthijsBurgh** [comment]
The environment variables are set for each arena in rsettings, which allows a correct initial pose in all arenas, without the need to change the WM files

**Comment by reinzor** [comment]
Isn't this defined by the initial_pose @LoyVanBeek  ?

-Rein

**Comment by LoyVanBeek** [comment]
Yes, the there is some SetInitialPose state. Setting that from robocup_knowledge deems best to me.

**Comment by reinzor** [comment]
So what to do with this PR?

-Rein

**Pull request closed without merging**
