### PR TITLE
feature(added parameters file which contains the possible launch files)

### PR DESCRIPTION
**Pull request by KevinDang74**
parameters necessary for the node auto_starter

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Please also create PR for SERGIO.

**Review by jlunenburg — APPROVED** [review]
In general, this looks okay. You might consider leaving out the '.launch' part, but you'd have to add this in the autostarter node.

**Comment by MatthijsBurgh** [comment]
@KevinDang74 still ok to merge?

**Comment by MatthijsBurgh** [comment]
@KevinDang74 Status??? Also create a PR for SERGIO.

**Comment by MatthijsBurgh** [comment]
Closing, because so old

**Pull request closed without merging**
